package co.istad.ai_interview_app.shared.enums.admin;

public enum NotificationEventType {
    COMPANY_VERIFICATION_SUBMITTED,
    COMPANY_VERIFICATION_APPROVED,
    COMPANY_VERIFICATION_REJECTED,
    COMPANY_VERIFICATION_REVISION_REQUESTED,

    JOB_POST_SUBMITTED,
    JOB_POST_APPROVED,
    JOB_POST_REJECTED,

    JOB_APPLICATION_SUBMITTED,
    JOB_APPLICATION_STATUS_CHANGED,

    AI_INTERVIEW_ASSIGNED,
    AI_INTERVIEW_COMPLETED,

    HUMAN_INTERVIEW_SCHEDULED,
    HUMAN_INTERVIEW_RESCHEDULED,
    HUMAN_INTERVIEW_CANCELLED,

    PROJECT_ASSIGNED,
    PROJECT_SUBMITTED,
    PROJECT_REVIEWED,

    MESSAGE_RECEIVED,

    INVOICE_ISSUED,
    INVOICE_PAID
}