DO $$
BEGIN
    IF to_regclass('job_applications') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'job_applications'::regclass
              AND conname = 'uk_job_applications_job_profile'
        ) THEN
            ALTER TABLE job_applications
                ADD CONSTRAINT uk_job_applications_job_profile
                    UNIQUE (job_post_id, job_seeker_profile_id);
        END IF;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS candidate_application_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL UNIQUE,
    moderator_profile_id bigint,
    review_status varchar(80) NOT NULL DEFAULT 'PENDING',
    decision_note text,
    reviewed_at timestamp with time zone,
    approved_at timestamp with time zone,
    forwarded_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    created_by varchar(100),
    updated_by varchar(100)
);

DO $$
BEGIN
    IF to_regclass('candidate_application_reviews') IS NOT NULL
       AND to_regclass('job_applications') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'candidate_application_reviews'::regclass
              AND conname = 'fk_candidate_application_reviews_application'
        ) THEN
            ALTER TABLE candidate_application_reviews
                ADD CONSTRAINT fk_candidate_application_reviews_application
                    FOREIGN KEY (application_id) REFERENCES job_applications(id);
        END IF;

        IF to_regclass('moderator_profiles') IS NOT NULL
           AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'candidate_application_reviews'::regclass
              AND conname = 'fk_candidate_application_reviews_moderator'
        ) THEN
            ALTER TABLE candidate_application_reviews
                ADD CONSTRAINT fk_candidate_application_reviews_moderator
                    FOREIGN KEY (moderator_profile_id) REFERENCES moderator_profiles(id);
        END IF;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_candidate_application_reviews_status
    ON candidate_application_reviews (review_status);

CREATE INDEX IF NOT EXISTS idx_candidate_application_reviews_forwarded_at
    ON candidate_application_reviews (forwarded_at);

CREATE TABLE IF NOT EXISTS human_interviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    moderator_profile_id bigint NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    meeting_url varchar(500) NOT NULL,
    status varchar(50) NOT NULL DEFAULT 'PENDING',
    result varchar(50),
    note text,
    completed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    created_by varchar(100),
    updated_by varchar(100)
);

DO $$
BEGIN
    IF to_regclass('human_interviews') IS NOT NULL
       AND to_regclass('job_applications') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'human_interviews'::regclass
              AND conname = 'fk_human_interviews_application'
        ) THEN
            ALTER TABLE human_interviews
                ADD CONSTRAINT fk_human_interviews_application
                    FOREIGN KEY (application_id) REFERENCES job_applications(id);
        END IF;

        IF to_regclass('moderator_profiles') IS NOT NULL
           AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'human_interviews'::regclass
              AND conname = 'fk_human_interviews_moderator'
        ) THEN
            ALTER TABLE human_interviews
                ADD CONSTRAINT fk_human_interviews_moderator
                    FOREIGN KEY (moderator_profile_id) REFERENCES moderator_profiles(id);
        END IF;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_human_interviews_application_status
    ON human_interviews (application_id, status);
