DO $$
BEGIN
    IF to_regclass('companies') IS NOT NULL THEN
        ALTER TABLE companies
            ADD COLUMN IF NOT EXISTS verification_status varchar(50),
            ADD COLUMN IF NOT EXISTS status varchar(50);

        UPDATE companies
        SET verification_status = 'PENDING_VERIFICATION'
        WHERE verification_status IS NULL;

        UPDATE companies
        SET status = 'PENDING'
        WHERE status IS NULL;

        ALTER TABLE companies
            ALTER COLUMN verification_status SET DEFAULT 'PENDING_VERIFICATION',
            ALTER COLUMN verification_status SET NOT NULL,
            ALTER COLUMN status SET DEFAULT 'PENDING',
            ALTER COLUMN status SET NOT NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS company_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uploaded_by_recruiter_profile_id bigint NOT NULL,
    document_type varchar(100) NOT NULL,
    document_url varchar(500) NOT NULL,
    status varchar(50) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    created_by varchar(100),
    updated_by varchar(100)
);

CREATE TABLE IF NOT EXISTS company_verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    moderator_profile_id bigint NOT NULL,
    decision varchar(50) NOT NULL,
    note text,
    verified_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    created_by varchar(100),
    updated_by varchar(100)
);

DO $$
BEGIN
    IF to_regclass('company_documents') IS NOT NULL
       AND to_regclass('companies') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'company_documents'::regclass
              AND conname = 'fk_company_documents_company'
        ) THEN
            ALTER TABLE company_documents
                ADD CONSTRAINT fk_company_documents_company
                    FOREIGN KEY (company_id) REFERENCES companies(id);
        END IF;

        IF to_regclass('recruiter_profiles') IS NOT NULL
           AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'company_documents'::regclass
              AND conname = 'fk_company_documents_uploaded_by_recruiter'
        ) THEN
            ALTER TABLE company_documents
                ADD CONSTRAINT fk_company_documents_uploaded_by_recruiter
                    FOREIGN KEY (uploaded_by_recruiter_profile_id) REFERENCES recruiter_profiles(id);
        END IF;
    END IF;

    IF to_regclass('company_verifications') IS NOT NULL
       AND to_regclass('companies') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'company_verifications'::regclass
              AND conname = 'fk_company_verifications_company'
        ) THEN
            ALTER TABLE company_verifications
                ADD CONSTRAINT fk_company_verifications_company
                    FOREIGN KEY (company_id) REFERENCES companies(id);
        END IF;

        IF to_regclass('moderator_profiles') IS NOT NULL
           AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'company_verifications'::regclass
              AND conname = 'fk_company_verifications_moderator'
        ) THEN
            ALTER TABLE company_verifications
                ADD CONSTRAINT fk_company_verifications_moderator
                    FOREIGN KEY (moderator_profile_id) REFERENCES moderator_profiles(id);
        END IF;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_company_documents_company
    ON company_documents (company_id);

CREATE INDEX IF NOT EXISTS idx_company_verifications_company_verified_at
    ON company_verifications (company_id, verified_at);

CREATE INDEX IF NOT EXISTS idx_companies_verification_status
    ON companies (verification_status);

CREATE INDEX IF NOT EXISTS idx_job_posts_public_discovery
    ON job_posts (status, expired_at);
